
services:
  selenium-hub:
    image: selenium/hub:4.1.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.1.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome-video:
    image: selenium/video:latest
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
    volumes:
      - ./videos:/videos

  firefox:
    image: selenium/node-firefox:4.1.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox-video:
    image: selenium/video:latest
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
    volumes:
      - ./videos:/videos
