name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Set ChromeDriver permissions
        run: sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Unitaria Test
        run: npm run test:unitaria

      - name: Run Funcional Test
        run: npm run test:funcional  

      - name: Run Integration Test
        run: npm run test:integracion

      - name: Run Regression Test
        run: npm run test:regresion
