name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

     - name: Install Chrome and ChromeDriver
  run: |
    sudo apt-get update
    sudo apt-get install -y wget
    sudo apt-get install -y chromium-browser
    CHROMIUM_PATH=$(which chromium-browser)
    wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver
    echo "CHROMIUM_PATH=$CHROMIUM_PATH"
    echo "chromium-browser is located at: $CHROMIUM_PATH"
    echo "CHROMIUM_PATH=$CHROMIUM_PATH" >> $GITHUB_ENV  # Exportando la variable


      - name: Run Funcional Test
        run: npm run test:funcional  

      - name: Run Regression Test
        run: npm run test:regresion  

      - name: Run Selenium Test
        run: npm run test  

      - name: Run Unitaria Test
        run: npm run test:unitaria 
